### ISSUE TITLE
When I run ros2 run gptserver gptserver, I encounter an error TypeError: 'type' object is not subscribable

### ISSUE THREAD

**Issue by von63** [NoneJou072/robochain#10]
(robochain) a@zmarm:~/ros2/gpt_ws$ ros2 run gpt_server gpt_server
WARNING:root:Could not import cv2, please install it to enable camera viewer.
Traceback (most recent call last):
  File "/home/a/ros2/gpt_ws/install/gpt_server/lib/gpt_server/gpt_server", line 11, in <module>
    load_entry_point('gpt-server', 'console_scripts', 'gpt_server')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/a/ros2/gpt_ws/build/gpt_server/gpt_server/gpt_server.py", line 23, in <module>
    import demo_env
  File "/home/a/ros2/gpt_ws/build/gpt_server/gpt_server/demo_env.py", line 4, in <module>
    from robopal.envs.task_ik_ctrl_env import PosCtrlEnv
  File "/home/a/pycharmprojects/robopal/robopal/envs/__init__.py", line 1, in <module>
    from .base import MujocoEnv
  File "/home/a/pycharmprojects/robopal/robopal/envs/base.py", line 8, in <module>
    from robopal.commons.renderers import MjRenderer
  File "/home/a/pycharmprojects/robopal/robopal/commons/renderers.py", line 14, in <module>
    class MjRenderer:
  File "/home/a/pycharmprojects/robopal/robopal/commons/renderers.py", line 110, in MjRenderer
    def add_visual_point(self, pos: np.ndarray | list[np.ndarray]):
TypeError: 'type' object is not subscriptable

**Comment by NoneJou072** [comment]
可能是 python 版本低于该库所要求的 3.9 版本

**Comment by DongRos** [comment]
你好你解决了么，我也这样

**Comment by NoneJou072** [comment]
更新：已修复该问题，robopal 库目前适配 python3.8 及以上版本
