### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain_openai'

### ISSUE THREAD

**Issue by lizhifeng12** [NoneJou072/robochain#14]
当我ros2 run gpt_server gpt_server时,出现错误 ModuleNotFoundError: No module named 'langchain_openai'
当我ros2 run gpt_server gpt_server时，出现：
Traceback (most recent call last):
  File "/home/ros2/gpt_ws/install/gpt_server/lib/gpt_server/gpt_server", line 33, in <module>
    sys.exit(load_entry_point('gpt-server==0.0.0', 'console_scripts', 'gpt_server')())
  File "/home/ros2/gpt_ws/install/gpt_server/lib/python3.10/site-packages/gpt_server/gpt_server.py", line 85, in main
    env = demo_env.make_env()
  File "/home/ros2/gpt_ws/install/gpt_server/lib/python3.10/site-packages/gpt_server/demo_env.py", line 93, in make_env
    env = GraspingEnv(
  File "/home/ros2/gpt_ws/install/gpt_server/lib/python3.10/site-packages/gpt_server/demo_env.py", line 31, in __init__
    self.init_pos, self.init_rot = self.kdl_solver.fk(self.robot.arm_qpos, rot_format='quaternion')
AttributeError: 'GraspingEnv' object has no attribute 'kdl_solver'. Did you mean: 'kd_solver'?
/home/ros2/.local/lib/python3.10/site-packages/glfw/__init__.py:914: GLFWError: (65537) b'The GLFW library is not initialized'
  warnings.warn(message, GLFWError)
[ros2run]: Process exited with failure 1
为什么呢？

**Comment by NoneJou072** [comment]
您好，原因是 robopal 库的 kdl_solver 现在已经更名成 kd_solver，您可以修改下程序，或者更新仓库
