### ISSUE TITLE
运行gpt_server后，报错could not allocate memory，使用free -h -w查看系统内存剩余26G

### ISSUE THREAD

**Issue by shjkea** [NoneJou072/robochain#16]
运行gpt_server后，报错could not allocate memory，mujoco终端打开但是显示loading，使用free -h -w查看系统内存剩余26G。运行robopal的demo，除demo_grasping.py其他均能运行，demo_grasping.py与运行gpt_server时的报错相同
![微信图片_20240415174327](https://github.com/NoneJou072/robochain/assets/166138369/06cd3a34-2c42-4ae9-9822-03de6336e396)

**Comment by NoneJou072** [comment]
请尝试降低mujoco版本，不要使用最新的3.1.4版本

**Comment by shjkea** [comment]
> 请尝试降低mujoco版本，不要使用最新的3.1.4版本

感谢，但是又报错AttributeError: 'DianaGraspMultiObjs' object has no attribute 'arm_qpos'
具体是这样的
Traceback (most recent call last):
  File "/home/lhe/gpt_ws/install/gpt_server/lib/gpt_server/gpt_server", line 33, in <module>
    sys.exit(load_entry_point('gpt-server', 'console_scripts', 'gpt_server')())
  File "/home/lhe/gpt_ws/build/gpt_server/gpt_server/gpt_server.py", line 85, in main
    env = demo_env.make_env()
  File "/home/lhe/gpt_ws/build/gpt_server/gpt_server/demo_env.py", line 93, in make_env
    env = GraspingEnv(
  File "/home/lhe/gpt_ws/build/gpt_server/gpt_server/demo_env.py", line 31, in __init__
    self.init_pos, self.init_rot = self.kd_solver.fk(self.robot.arm_qpos, rot_format='quaternion')
AttributeError: 'DianaGraspMultiObjs' object has no attribute 'arm_qpos'
[ros2run]: Segmentation fault
robopal已经是0.3.0版本，请问是出了什么问题

**Comment by NoneJou072** [comment]
您好，由于 robopal 库不断在迭代更新，原有的 api 发生改变，例如 arm_qpos 现在已经更改为 get_arm_qpos()。已在 robochain 中更新
