### ISSUE TITLE
 ros2 run gpt_server gpt_server ValueError

### ISSUE THREAD

**Issue by wiselinpm** [NoneJou072/robochain#19]
yahboom@yahboom-virtual-machine:~/gpt_ws$ ros2 run gpt_server gpt_server
INFO:root:Initializing ROS...
[INFO] [1716243576.532879547] [gpt_server]: Gpt server has init.
INFO:root:Done.
INFO:root:Initializing Simulator...
INFO:root:Activated agents: ['arm0']
/home/yahboom/.local/lib/python3.10/site-packages/glfw/__init__.py:914: GLFWError: (65544) b'Wayland: Window position retrieval not supported'
  warnings.warn(message, GLFWError)
INFO:root:Done.
Traceback (most recent call last):
  File "/home/yahboom/gpt_ws/install/gpt_server/lib/gpt_server/gpt_server", line 33, in <module>
    sys.exit(load_entry_point('gpt-server==0.0.0', 'console_scripts', 'gpt_server')())
  File "/home/yahboom/gpt_ws/install/gpt_server/lib/python3.10/site-packages/gpt_server/gpt_server.py", line 95, in main
    env.step(env.action)
  File "/home/yahboom/gpt_ws/install/robopal/lib/python3.10/site-packages/robopal/envs/robot.py", line 65, in wrapper
    ret = func(self, *args, **kwargs)
  File "/home/yahboom/gpt_ws/install/robopal/lib/python3.10/site-packages/robopal/envs/robot.py", line 76, in step
    joint_inputs = self.controller.step_controller(action)
  File "/home/yahboom/gpt_ws/install/robopal/lib/python3.10/site-packages/robopal/controllers/task_ik_controller.py", line 64, in step_controller
    ret[agent] = self.ik(p_goal, r_goal, agent)
  File "/home/yahboom/gpt_ws/install/robopal/lib/python3.10/site-packages/robopal/controllers/task_ik_controller.py", line 77, in ik
    x, _ = minimize.least_squares(x, ik_target, self.robot.mani_joint_bounds[agent], jacobian=jac_target, eps=1e-6, verbose=0)
  File "/home/yahboom/.local/lib/python3.10/site-packages/mujoco/minimize.py", line 247, in least_squares
    r = residual(x)
  File "/home/yahboom/gpt_ws/install/robopal/lib/python3.10/site-packages/robopal/controllers/task_ik_controller.py", line 75, in <lambda>
    ik_target = lambda x: self._ik_res(x, pos=pos, quat=quat, reg_target=x_prev, radius=radius, reg=.01, agent=agent)
  File "/home/yahboom/gpt_ws/install/robopal/lib/python3.10/site-packages/robopal/controllers/task_ik_controller.py", line 107, in _ik_res
    return np.hstack((res_pos, res_quat, res_reg))
  File "/home/yahboom/.local/lib/python3.10/site-packages/numpy/core/shape_base.py", line 357, in hstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 2 has 2 dimension(s)
[ros2run]: Segmentation fault

**Comment by wiselinpm** [comment]
按照文档进行了部署，不可以用

**Comment by NoneJou072** [comment]
问题的原因是你的mujoco版本为 3.1.5，而 robopal 要求的mujoco版本为 3.1.4。不过这个问题在今天已经修复了，您可以更新下 robopal
